/******************************************************************************
*                                                                             *
*   Module:     messages.cpp                                                  *
*                                                                             *
*   Date:       05/04/04                                                      *
*                                                                             *
*   Copyright (c) 2002-2004 Goran Devic                                       *
*                                                                             *
*   Author:     Goran Devic                                                   *
*                                                                             *
*   This source code and produced executable is copyrighted by Goran Devic.   *
*   This source, portions or complete, and its derivatives can not be given,  *
*   copied, or distributed by any means without explicit written permission   *
*   of the copyright owner. All other rights, including intellectual          *
*   property rights, are implicitly reserved. There is no guarantee of any    *
*   kind that this software would perform, and nobody is liable for the       *
*   consequences of running it. Use at your own risk.                         *
*                                                                             *
*******************************************************************************

    Module Description:

        This Project creates a program that generates the include file
        containing the custom messages based on the input text file.

        The messages are stored encoded in a simple way to avoid detection
        by the casual observer on the object file.

*******************************************************************************
*   Include Files                                                             *
******************************************************************************/

#include "stdafx.h"
#include "iostream.h"
#include "fstream.h"
#include <string.h>

typedef unsigned char BYTE;

static char inputFileName[] = "messages.txt";
static char outputFileName[]= "messages.h";

ifstream inFile;
ofstream outFile;

char line[1024];
char token[32];

// This is the encoding key:
static BYTE key[13] = { 0xDF, 0x38, 0x82, 0xF5, 0x5A, 0xA9, 0x90, 0x16, 0xB2, 0x27, 0xCC, 0x63, 0x7E };
static BYTE key2[13] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
// The same key exists in the linice/messages.c

static int nPos = 0;
static int checksum = 0;
static int maxMessages = 0;

/******************************************************************************
*   Main()                                                                    *
******************************************************************************/
int main(int argc, char* argv[])
{
    inFile.open(inputFileName, ios::in);
    outFile.open(outputFileName, ios::out);

    if(!inFile)
    {
        cerr << "Can't open input file " << inputFileName << endl;
    }
    else
    {
        if(!outFile)
        {
            cerr << "Can't open output file " << outputFileName << endl;
        }
        else
        {
            // Print the include file header:

outFile<<"/******************************************************************************\n";
outFile<<"*                                                                             *\n";
outFile<<"*   Module:     messages.h                                                    *\n";
outFile<<"*                                                                             *\n";
outFile<<"*   Copyright (c) 2000-2004 Goran Devic                                       *\n";
outFile<<"*                                                                             *\n";
outFile<<"*   Author:     Goran Devic                                                   *\n";
outFile<<"*                                                                             *\n";
outFile<<"*   *** This file is automatically generated - DO NOT EDIT ! ***              *\n";
outFile<<"*                                                                             *\n";
outFile<<"*   This file is generated by the tools/messages project based on the set     *\n";
outFile<<"*   of custom messages. Please see that project for details.                  *\n";
outFile<<"*                                                                             *\n";
outFile<<"******************************************************************************/\n";
outFile<<"\n"<<endl;

outFile<<"#define MAX_MESSAGES         108\n\n";

outFile<<"static char *messages[MAX_MESSAGES+1] = {\n";

            while(!inFile.eof())
            {
                inFile.getline(line, 1024);

                nPos = 0;

outFile<<"  \"";

                // Store the string len as the first 2 bytes
                int nLen = strlen(line);
sprintf(token, "\\x%02X\\x%02X", nLen & 0xFF, (nLen>>8) & 0xFF);
outFile<<token;

                // Parse the line of message and encode it
                for( int i=0; line[i]; i++)
                {
                    // Encoding function
                    BYTE code = line[i] ^ key[nPos % 13];
                    
                    nPos++;

                    sprintf(token, "\\x%02X", code);

                    outFile<<token;
                }
outFile<<"\","<<endl;
            }

outFile<<"};"<<endl;

            inFile.close();
            outFile.close();
        }
    }

	return 0;
}

