#=============================================================================
#
# 	Makefile for test modules (kernel 2.6)
#
#	Run: make -C /usr/src/linux-version SUBDIRS=$PWD modules
#
#   (or use local ./compile script)
#
#=============================================================================

obj-m := module.o modlp.o modscope.o
